# Modify it to your installation path...
INCLUDE = /Library/gurobi700/mac64/include/
LIBRARY = /Library/gurobi700/mac64/lib/
all:
	g++ tsp_c.cpp -o tsp -I ${INCLUDE} -L${LIBRARY} -lgurobi_c++ -lgurobi70